/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: 'var(--color-brand)',
        success: 'var(--color-success)',
        danger: 'var(--color-danger)',
        duck: 'var(--color-duck-yellow)',
        canvas: 'var(--color-canvas)',
        'canvas-water': 'var(--color-canvas-water)',
        muted: 'var(--color-muted)',
        line: 'var(--color-line)',
        ink: 'var(--color-ink)',
        'surface-brand': 'var(--color-surface-brand)',
        'surface-brand-subtle': 'var(--color-surface-brand-subtle)',
        'surface-warm': 'var(--color-surface-warm)',
        'surface-success': 'var(--color-surface-success)',
        'surface-water': 'var(--color-surface-water)',
        'surface-brand-pale': 'var(--color-surface-brand-pale)',
        'line-brand': 'var(--color-line-brand)',
        'line-success': 'var(--color-line-success)',
        'brand-muted': 'var(--color-brand-muted)',
        'goal-loss': 'var(--color-goal-loss)',
        'goal-maintain': 'var(--color-goal-maintain)',
        'goal-gain': 'var(--color-goal-gain)',
        info: 'var(--color-info)',
        'plant-dot': 'var(--color-plant-dot)',
        'plant-dark': 'var(--color-plant-dark)',
        'plant-light': 'var(--color-plant-light)',
        food: 'var(--color-food)',
        'neutral-subtle': 'var(--color-neutral-subtle)',
        'water-line': 'var(--color-water-line)',
      },
      maxWidth: {
        screen: '390px',
      },
      borderRadius: {
        control: '10px',
        element: '14px',
        'card-sm': '16px',
        card: '20px',
        pill: '50px',
      },
      boxShadow: {
        card: '0 2px 16px rgba(0,0,0,0.04)',
        float: '0 2px 10px rgba(0,0,0,0.08)',
        plate: '0 3px 8px rgba(0,0,0,0.12)',
      },
      borderWidth: {
        1.5: '1.5px',
        2.5: '2.5px',
      },
      fontSize: {
        caption: '11px',
        label: '13px',
        body: '15px',
        input: '17px',
        heading: '30px',
        'heading-lg': '34px',
        display: '48px',
      },
      letterSpacing: {
        label: '0.4px',
        heading: '-0.4px',
        badge: '0.2px',
        'heading-lg': '-0.5px',
        em: '0.04em',
      },
      lineHeight: {
        body: '1.65',
        bubble: '1.4',
        heading: '1.15',
        subheading: '1.16',
        number: '1.05',
      },
      zIndex: {
        1: '1',
        100: '100',
      },
    },
  },
  plugins: [],
};
